version: "3"
services:

  prometheus:
    image: prom/prometheus:latest
    hostname: prometheus
    user: "1000:1000"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./prometheus:/prometheus
    ports:
      - "9390:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--web.enable-admin-api'
      - '--storage.tsdb.retention.time=7d'
      - '--storage.tsdb.path=/prometheus'
  alertmanager:
    image: prom/alertmanager
    hostname: alertmanager
    user: "1000:1000"
    volumes:
      - ./alertmanager:/etc/prometheus/alertmanager
    ports:
      - "9093:9093"
  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    user: root
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./dashboards/:/etc/grafana/provisioning/dashboards/
      - ./datasources/:/etc/grafana/provisioning/datasources/
    ports:
      - "3000:3000"
