{
 "title": "celestia-dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Panel Title", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 } },
  { "title": "node-exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  { "title": "Validator Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Distance from Height",
   "type": "stat",
   "description": "The distance between validator's latest committed height and the network's consensus height",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "celestia_consensus_latest_block_height - ignoring(validator_address) celestia_consensus_validator_last_signed_height ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missed Blocks",
   "type": "stat",
   "description": "The amount of blocks missed during a given time ",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "celestia_consensus_validator_missed_blocks",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State Syncing ",
   "type": "stat",
   "description": "If 1, it's syncing. If 0, it's synced",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(celestia_consensus_state_syncing * 100) / ignoring(validator_address) celestia_consensus_validators_power",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Power",
   "type": "stat",
   "description": "Validator's voting power ",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(celestia_consensus_validator_power * 100) / ignoring(validator_address) celestia_consensus_validators_power",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Global Network Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Active Validators",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "celestia_consensus_validators", "legendFormat": "{{__name__}}" },
    {
     "expr": "celestia_consensus_missing_validators",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Current network height",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "celestia_consensus_height", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mean Block Processing Time ",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "celestia_state_block_processing_time_bucket",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}